name: Deploy Flutter Web Demo

# Add permissions for deployment
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Setup Flutter
      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          
      # Get dependencies
      - name: Get dependencies
        run: flutter pub get
        
      # Build web
      - name: Build web
        run: |
          cd example
          flutter build web --release --base-href "/color_palette_plus/"
          
      # Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
          force_orphan: true
          publish_branch: gh-pages
          enable_jekyll: false